version: "3"

services:
  app:
    build: .
    volumes:
      - .:/code
    expose:
      - 8000
    networks:
      - hrplus-network
    depends_on:
      - mongo

  panel:
    image: node:12.16.2-alpine
    container_name: hr-plus-panel
    volumes:
      - './panel:/code'
    working_dir: /code
    ports:
      - "8080:8080"
    networks:
      - hrplus-network

  nginx:
    image: nginx
    container_name: hr_plus_webserver
    ports:
      - '8888:80'
    volumes:
      - './docker-compose/nginx/site.conf:/etc/nginx/conf.d/default.conf'
      - '.:/code'
    networks:
      - hrplus-network
    depends_on:
      - app

  mongo:
    image: mongo:4.2
    container_name: hr_plus_mongo
    volumes:
      - "hr_plus_mongodb:/data/db"
    networks:
      hrplus-network:
        aliases:
          - mongodb

  redis:
    image: redis:5.0.6-alpine
    container_name: hr_plus_redis
    volumes:
      - 'hr_plus_redis:/data'
    networks:
      hrplus-network:
        aliases:
          - redis

volumes:
  hr_plus_mongodb:
  hr_plus_redis:

networks:
  hrplus-network:
    driver: bridge
