version: "3"

services:
  app:
    build: .
    volumes:
      - .:/code
    expose:
      - 8000
    networks:
      - hrplus-network
    depends_on:
      - postgres

  panel:
    build:
      context: ./panel
      dockerfile: Dockerfile
    container_name: hr-plus-panel
    volumes:
      - './panel:/code'
      - /code/node_modules
    networks:
      - hrplus-network
    depends_on:
      - app

  nginx:
    image: nginx
    container_name: hr_plus_webserver
    ports:
      - '8888:80'
    depends_on:
      - panel
    volumes:
      - './docker-compose/nginx/site.conf:/etc/nginx/conf.d/default.conf'
      - '.:/code'
    networks:
      - hrplus-network

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: "/var/lib/postgresql/data"
    networks:
      hrplus-network:
        aliases:
          - postgresdb
    volumes:
      - "hrplus_postgres:/var/lib/postgresql/data"

  redis:
    image: redis:5.0.6-alpine
    container_name: hr_plus_redis
    volumes:
      - 'hr_plus_redis:/data'
    networks:
      hrplus-network:
        aliases:
          - redis

volumes:
  hrplus_postgres:
  hr_plus_redis:

networks:
  hrplus-network:
    driver: bridge
