version: "3"

services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
#    ports:
#      - "8888:8000"
    expose:
      - 8000
    networks:
      - hrplus-network
    depends_on:
      - postgres

  nginx:
    image: nginx
    container_name: hr_plus_webserver
    ports:
      - '8888:80'
    depends_on:
      - app
    volumes:
      - './docker-compose/nginx/site.conf:/etc/nginx/conf.d/default.conf'
      - '.:/code'
    networks:
      - hrplus-network

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: "/var/lib/postgresql/data"
    networks:
      hrplus-network:
        aliases:
          - postgresdb
    volumes:
      - "hrplus_postgres:/var/lib/postgresql/data"

volumes:
  hrplus_postgres:

networks:
  hrplus-network:
    driver: bridge
